### ISSUE TITLE
test views

### ISSUE THREAD

**Issue by constantinpape** [mobie/zebrafish-lm-project#10]
I have added test views for grids containing segmentations with names only updated in the views now. They are in `data/membrane/misc/views/test_views.json` To test in MoBIE:
- Open this project
- In the default dataset, add the views via `RightClick->Load Additional Views->Project->test_views.json`
- This will add two new views: `test->merged-grid` and `test->transformed-grid`

**transformed-grid:** contains a grid view applied to cropped images and segmentations and uses `sourceNamesAfterTransform` in the crops and grids

**merged-grid:** contains a nested merged grid view and refers to the merged segmentation grid in `segmentationDisplays`
(Note: setting up this example was a bit more complicated, so I am not 100% sure if everything is correct already.)

As expected, both grids cannot be loaded right now.

**Comment by tischi** [comment]
@constantinpape 
Regarding the **merged-grid**: The code is getting stuck at creating the `all-images`. I will try to find out why, but if you have an idea, let me know:
```
Creating MergedGridSource: images-well1
Creating MergedGridSource: segs-well1
Creating MergedGridSource: images-well2
Creating MergedGridSource: segs-well2
Creating MergedGridSource: all-images
```

**Comment by constantinpape** [comment]
@tischi as I noted above I am not 100% sure if the `merged-grid` is correct. Does the default view in https://github.com/mobie/covid-if-project work?

**Comment by tischi** [comment]
Not really, but that seems to be another issue:

```
new MoBIE( "https://github.com/mobie/covid-if-project", MoBIESettings.settings().gitProjectBranch( "main" ).imageDataFormat( ImageDataFormat.OmeZarr ) );
```

```
18:29:34.966 [main] WARN sc.fiji.bdvpg.scijava.services.SourceAndConverterService - Overriding action Change Random Coloring Seed [ Ctrl L ]
Exception in thread "pool-3-thread-2" java.lang.UnsupportedOperationException: Could not find multiscales at 
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.getMultiscale(N5OMEZarrImageLoader.java:258)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.initSetups(N5OMEZarrImageLoader.java:169)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.fetchSequenceDescriptionAndViewRegistrations(N5OMEZarrImageLoader.java:124)
	at org.embl.mobie.io.ome.zarr.loaders.N5OMEZarrImageLoader.<init>(N5OMEZarrImageLoader.java:118)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrOpener.readFile(OMEZarrOpener.java:36)
	at org.embl.mobie.io.ome.zarr.openers.OMEZarrOpener.openFile(OMEZarrOpener.java:29)
	at org.embl.mobie.viewer.source.SpimDataOpener.openOmeZarrData(SpimDataOpener.java:123)
	at org.embl.mobie.viewer.source.SpimDataOpener.openSpimData(SpimDataOpener.java:71)
	at org.embl.mobie.viewer.MoBIE.openSourceAndConverter(MoBIE.java:293)
	at org.embl.mobie.viewer.MoBIE.lambda$openSourceAndConverters$0(MoBIE.java:188)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by constantinpape** [comment]
> Not really, but that seems to be another issue:

Yes, that looks like an issue with reading the ome.zarr file. I will check the merged-grid view again later and let you know if I find any issue in the json.

**Comment by tischi** [comment]
If you look at this could you please rename the two views to start with `test-`? `test-transformed-grid` and `test-merged-grid`?!
Currently view names need to be unique and they are very close to crashing with some in the actual project...

**Comment by constantinpape** [comment]
@tischi I have renamed both views now to start with `test-`.

For `test-transformed-grid` I currently get the following error:
```
Exception in thread "Thread-8" java.lang.IllegalArgumentException: Sources of type bdv.util.ResampledSource are currently not supported in MoBIE.fetchTableRootSources.
	at org.embl.mobie.viewer.MoBIE.fetchTableRootSources(MoBIE.java:448)
	at org.embl.mobie.viewer.MoBIE.fetchTableRootSources(MoBIE.java:435)
	at org.embl.mobie.viewer.MoBIE.fetchTableRootSources(MoBIE.java:435)
	at org.embl.mobie.viewer.MoBIE.fetchTableRootSources(MoBIE.java:435)
	at org.embl.mobie.viewer.MoBIE.loadPrimarySegmentsTables(MoBIE.java:407)
	at org.embl.mobie.viewer.MoBIE.loadPrimarySegmentsTables(MoBIE.java:524)
	at org.embl.mobie.viewer.view.ViewManager.loadTablesAndCreateImageSegments(ViewManager.java:463)
	at org.embl.mobie.viewer.view.ViewManager.showSegmentationDisplay(ViewManager.java:418)
	at org.embl.mobie.viewer.view.ViewManager.showSourceDisplay(ViewManager.java:349)
	at org.embl.mobie.viewer.view.ViewManager.show(ViewManager.java:297)
	at org.embl.mobie.viewer.ui.UserInterfaceHelper.lambda$null$1(UserInterfaceHelper.java:456)
	at java.lang.Thread.run(Thread.java:748)
```

For `test-merged-grid`, I waited very long; and then a lot of the following errors appeared:
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 69259
	at net.imglib2.cache.ref.SoftRefLoaderCache.get(SoftRefLoaderCache.java:145)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:76)
	at net.imglib2.cache.ref.WeakRefVolatileCache.getBlocking(WeakRefVolatileCache.java:484)
	at net.imglib2.cache.ref.WeakRefVolatileCache.access$000(WeakRefVolatileCache.java:53)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:531)
	at net.imglib2.cache.ref.WeakRefVolatileCache$FetchEntry.call(WeakRefVolatileCache.java:508)
	at net.imglib2.cache.queue.FetcherThreads$Fetcher.run(FetcherThreads.java:181)
```
So I assume that this is actually the known problem that `mergedGrid` fails if the individual sources are too large (which is the case here because each individual source is a 3d volume).

I suggest we remove `test-merged-grid` here and instead test the merged-grid for a small view from the covid-if dataset.
I will start uploading the data to s3 tomorrow and can then just create the test case. What do you think?

**Comment by tischi** [comment]
> For test-transformed-grid I currently get the following error

This will be fixed once we merge [this](https://github.com/mobie/mobie-viewer-fiji/pull/517).

> I suggest we remove test-merged-grid here and instead test the merged-grid for a small view from the covid-if dataset.

I agree.

**Comment by constantinpape** [comment]
> > For test-transformed-grid I currently get the following error
> 
> This will be fixed once we merge [this](https://github.com/mobie/mobie-viewer-fiji/pull/517).
> 
> > I suggest we remove test-merged-grid here and instead test the merged-grid for a small view from the covid-if dataset.
> 
> I agree.

Ok, I have remved `test-merged-grid` now. I will ping you once I have a test view for this in `covid-if-project`, but I am not sure if I have time for this today.

Let me know when you thing the issue with the transformedGrid is fixed, then I can give it a try.

**Comment by tischi** [comment]
The test-transformed-grid works but does not show any sources:

<img width="568" alt="image" src="https://user-images.githubusercontent.com/2157566/140894910-b5752ff8-3dfa-4b0e-b2aa-9c99281952f5.png">

Maybe a something wrong with the JSON? 

I wonder whether we actually need this, because the `small-grid-view` works and should cover similar functionality?

**Comment by constantinpape** [comment]
> Maybe a something wrong with the JSON?

Maybe the crop is wrong, I will double check. But it's already a big step that it opens at all, so you can also go ahead and merge the relevant changes already.

> I wonder whether we actually need this, because the `small-grid-view` works and should cover similar functionality?

Yes, we need it; the small grid does not contain `sourceNamesAfterTransform` and thus does not check for a segmentation source that is just created in the view.

**Comment by constantinpape** [comment]
@tischi I have updated the test view now to use a rotation by 45 degree instead of the crop; that should be less error prone.
Could you check if the view looks better now?

**Comment by tischi** [comment]
works now! 

I have an error when selecting an image segment, but I think this is a bug in MoBIE:

```
Exception in thread "Thread-7" java.lang.NullPointerException
	at org.embl.mobie.viewer.bdv.view.SegmentationSliceView.adaptPosition(SegmentationSliceView.java:156)
	at org.embl.mobie.viewer.bdv.view.SegmentationSliceView.focusEvent(SegmentationSliceView.java:142)
	at org.embl.mobie.viewer.bdv.view.SegmentationSliceView.focusEvent(SegmentationSliceView.java:27)
	at de.embl.cba.tables.select.DefaultSelectionModel.lambda$focus$1(DefaultSelectionModel.java:113)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tischi** [comment]
The issue is that the sources specified in the segmentation display have different names than the ones that hold the tables:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/2157566/140910547-b52084a7-930f-4d45-a9bc-8bc8c82067f6.png">

**Comment by constantinpape** [comment]
> The issue is that the sources specified in the segmentation display have different names than the ones that hold the tables:

Yes, that's because the `..._seg_transformed` sources are only created in the view. You somehow need to inherit the table as well in the viewer.

**Comment by tischi** [comment]
I modified the code accordingly and it seems to work 🥳 

```
	private ArrayList< List< TableRowImageSegment > > loadPrimarySegmentsTables(SegmentationSourceDisplay segmentationDisplay, String table )
	{
		final List< String > segmentationDisplaySources = segmentationDisplay.getSources();
		final ConcurrentHashMap< String, Set< Source > > sourceNameToRootSources = new ConcurrentHashMap();

		for ( String sourceName : segmentationDisplaySources )
		{
			Set< Source > rootSourceNames = ConcurrentHashMap.newKeySet();
			Utils.fetchRootSources( getSourceAndConverter( sourceName ).getSpimSource(), rootSourceNames );
			sourceNameToRootSources.put( sourceName, rootSourceNames );
		}

		// TODO: make parallel
		final ArrayList< List< TableRowImageSegment > > primaryTables = new ArrayList<>();
		for ( String displayedSourceName : segmentationDisplaySources )
		{
			final Set< Source > rootSources = sourceNameToRootSources.get( displayedSourceName );
			for ( Source rootSource : rootSources )
			{
				addPrimaryTable( table, primaryTables, rootSource.getName(), displayedSourceName );
			}
		}

		return primaryTables;
	}
```

We can select segments in transformed images.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/2157566/140913636-bc4f6b81-ccc8-4adf-bd68-fc58dfe47397.png">

**Comment by constantinpape** [comment]
Works for me as well with the new version on mobie-beta. I will close this issue and ping you once I have a test view for the mergedGrid with segmentation.
